# fly.toml app configuration file generated for twilight-haze-2909 on 2023-09-04T01:03:29+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twilight-haze-2909"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
